### ISSUE TITLE
Suggestion: Display history as rows with expandable content

### ISSUE THREAD

**Issue by AnEmortalKid** [autorolltables/autorolltables.github.io#50]
Like so: http://imgur.com/a/QdChS

The history text area can get quite long, and browsing through it to find something you want (after rolling a bunch of things) can be a bit tedious. Having these expandable rows would make it faster to filter out what we're looking for. Additionally, we could eventually have an X on the row and selecting it would delete that element.

**Comment by dangeratio** [comment]
Added with: 0e415d2611e92ca0abb6f5411ceee84279d0b152

**Comment by dangeratio** [comment]
Added removal feature with: 4f23f1ab7a73480f0cf030a9787293d12b9c9f89
