### ISSUE TITLE
Campaign Descriptions

### ISSUE THREAD

**Issue by ghost** [autorolltables/autorolltables.github.io#56]
> Suggested Use: Use when you start a new campaign/world. Choose 1 off of each list, and 5 off of the adjectives list.

The data generated only supplies 1 off of the adjectives list.

**Comment by dangeratio** [comment]
Thanks for finding this.  I'll add 4 more adjective rolls so you get the full list and don't have to re-roll multiple times.

**Comment by dangeratio** [comment]
Fixed with 1f0dc4b906587c32f8032c7c3e5d40d4a54c9948
